name: RTS_digitization_experiment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyterlab=4.2.3
  - pandas=1.5.3
  - geopandas=0.9
  - seaborn=0.13.2
  - matplotlib=3.8.4
  - rasterio=1.3.10
  - shapely=2.0.4
  - numpy=1.26.4
